import type { KnipConfig } from 'knip';

// Only what Knip's static analysis cannot follow: a string inside another tool's config, or a subprocess binary.
const config: KnipConfig = {
  entry: [
    // playwright.config.ts's `webServer.command` is a shell string.
    'scripts/serve-export.mjs',
    // playwright.config.ts's `testMatch` is a regex against a conditionally-spread project.
    'e2e/signed-in.setup.ts',
    // Named only as a string in stryker.config.mjs's `configFile`.
    'vitest.mutation.config.mts',
    // Run by the k6 binary (scripts/load-test.mjs), never imported.
    'load/*.js',
    // k6 proofs (load/proofs/README.md), run by the k6 binary; the fixture generator is run by hand.
    'load/proofs/*.js',
    'load/proofs/browser/*.js',
    'load/proofs/fixtures/generate.mjs',
  ],
  ignore: [
    // Generated by `supabase gen types`; CI's schema-diff check keeps it honest.
    'src/app/data/database.types.ts',
  ],
  ignoreBinaries: [
    // A standalone binary (.github/actions/setup-supabase-cli in CI), never an npm dependency.
    'supabase',
    // A standalone binary too, installed by grafana/setup-k6-action or locally.
    'k6',
    // The Postgres client scripts/load-db-report.mjs reads statistics with, as supabase/splinter.sh does.
    'psql',
  ],
  ignoreDependencies: [
    // Invoked as `npx lhci autorun`; the bin is named `lhci`, so Knip cannot match it back to the package.
    '@lhci/cli',
    // k6/http, k6/metrics and friends are built into the k6 binary, not an npm package.
    'k6',
  ],
};

export default config;
