import type { KnipConfig } from 'knip';

// Next.js (App Router), Vitest and Stryker are all detected by Knip's
// built-in plugins from next.config.ts/vitest.config.mts/stryker.config.mjs
// with no extra config -- App Router's page.tsx/layout.tsx entry points,
// the *.test.{ts,tsx} suite, and the mutation-test run all resolve without
// anything below. What's listed here are exactly the places Knip's static
// analysis can't follow: a string embedded inside another tool's config,
// or a binary invoked as a subprocess rather than imported.
const config: KnipConfig = {
  entry: [
    // playwright.config.ts's `webServer.command` is a shell string
    // ("node scripts/serve-export.mjs ...") Knip doesn't parse as an import.
    'scripts/serve-export.mjs',
    // playwright.config.ts's `testMatch: /signed-in\.setup\.ts/` -- a
    // regex against a conditionally-spread project, not a static import.
    'e2e/signed-in.setup.ts',
    // Referenced only via stryker.config.mjs's `configFile:
    // 'vitest.mutation.config.mts'` string.
    'vitest.mutation.config.mts',
  ],
  ignore: [
    // Generated by `supabase gen types`; kept honest by CI's schema-diff
    // check (ci.yml), not by Knip -- see CLAUDE.md guardrail #3. Knip
    // doesn't cover unused i18n keys either (web/src/app/i18n/parity.test.ts
    // owns that), but that's a file it never looks inside, not an ignore.
    'src/app/data/database.types.ts',
  ],
  ignoreBinaries: [
    // The Supabase CLI: a standalone binary installed by
    // .github/actions/setup-supabase-cli (CI) or by the developer locally,
    // never an npm dependency of this project.
    'supabase',
  ],
  ignoreDependencies: [
    // scripts/lighthouse.mjs invokes it as `npx lhci autorun` -- Knip's
    // binary-usage detection resolves a bin invocation back to its
    // package by name (this is how `serve`, invoked the same way from
    // scripts/serve-export.mjs, needs no entry here), but `@lhci/cli`'s
    // own bin is named `lhci`, not `@lhci/cli`, so that match fails.
    '@lhci/cli',
  ],
};

export default config;
