import { defineConfig } from 'vitest/config';

import { MUTATE_TARGETS, NO_COVERAGE_FLOOR } from './mutation-targets.mjs';

// Declared before PER_FILE_FLOOR: ci.yml's vitest-coverage-report-action regex-scans this file for the first `statements: N`.
const GLOBAL_COVERAGE_THRESHOLDS = {
  statements: 99,
  branches: 99,
  functions: 99,
  lines: 99,
};

const PER_FILE_FLOOR = {
  statements: 100,
  functions: 100,
  branches: 100,
  lines: 100,
};

const perFileThresholds = Object.fromEntries(
  MUTATE_TARGETS.filter((path) => !NO_COVERAGE_FLOOR.includes(path)).map(
    (path) => [path, PER_FILE_FLOOR],
  ),
);

export default defineConfig({
  test: {
    environment: 'node',
    setupFiles: ['./vitest.setup.ts'],
    include: ['src/**/*.test.{ts,tsx}'],
    // supabase.ts builds a client at import time and throws unless these are set and URL-shaped.
    env: {
      NEXT_PUBLIC_SUPABASE_URL: 'https://example.supabase.co',
      NEXT_PUBLIC_SUPABASE_ANON_KEY: 'test-anon-key',
    },
    coverage: {
      provider: 'v8',
      // `json-summary` feeds ci.yml's vitest-coverage-report-action.
      reporter: ['text', 'lcov', 'json-summary'],
      include: ['src/app/**/*.{ts,tsx}'],
      exclude: [
        'src/app/**/types.ts',
        // Generated by `supabase gen types typescript`.
        'src/app/data/database.types.ts',
        'src/app/i18n/*.json',
        '**/*.d.ts',
        // Routing/auth glue and the Leaflet wrapper: verified by Playwright, not unit tests.
        'src/app/layout.tsx',
        'src/app/page.tsx',
        'src/app/login/page.tsx',
        'src/app/useSignOut.ts',
        'src/app/login/useGoogleSignIn.ts',
        'src/app/login/useAuthRedirect.ts',
        'src/app/login/useDemoSignIn.ts',
        'src/app/data/auth.ts',
        'src/app/components/Map/index.tsx',
      ],
      thresholds: {
        ...GLOBAL_COVERAGE_THRESHOLDS,
        // On, it wrote the local measurement back into this file, turning a green local run into a red PR.
        autoUpdate: false,
        // Built from the shared list rather than listed by hand, so it cannot drift from what Stryker mutates.
        ...perFileThresholds,
      },
    },
  },
});
